
---

apiVersion: v1
kind: Secret
metadata:
  name: smartcollect-db-user
  namespace: smartcollect-db
type: kubernetes.io/basic-auth
data:
  username: "cG9zdGdyZXM="
  password: "cG9zdGdyZXM="

---

apiVersion: v1
kind: Secret
metadata:
  name: smartcollect-db-superuser
  namespace: smartcollect-db

---